version: "3.8"

services:
  painel-retencao:
    build: .
    container_name: painel-retencao-app
    restart: unless-stopped
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./configs:/app/configs
      - ./queries:/app/queries
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
